language: node_js
node_js:
- 6.9.5
deploy:
  provider: heroku
  app: brandybucks
  api_key:
    secure: ZP9FcbX6IqXeqhWkkkR3wYCZIuxkVWOlsVuGQ+W0TtG4l8BLN6/jAXHzW+fQF1NT4rJ58MqlLDm4gI0h1pBuCHa6DxBVkjDjYp0jSpFwSLFXXp2U5kQzCpbiHVx/Q2iy93im3+FBcyDPcc7bub2GtW7MgyGN5aklqN9Yawn/Xc1R4FYCCePk5ULy5IyV9suwqVpWvch9jI839gLPUtE8e8Ep4Dx8/hFhAEVyS54DN4eurwYbcbYsZE7lTdB1eEe/MB7GaCTYhlLpnc0bg9mLaDiouYVhu4VJltx/WFgQJngPJDr1HDmqMnpJ4CXhQOaCsgo3tmxfa55Kju4IA9iIAP6GNkIfWTwrYh14mUq+9T9gV6NNvk4RjXeCMzZvaKtUp73277/QvS+a8bw1r2FbqUPCW6A+pUQSKEsb5Iqs0+f37Zq/BWqOhzXFWInBaaMCkE2On8UJMW3AXEj4wyZ1gJXRyvYykxfC+cDr3jnjI0iKOCg2gcW8ioxe6AeSSpJ9BaFqJngHjWRB5DP+UEQgy7s4HWXujFcjJz4feWKDiPCChytXQpYHI59idpGmMjjTz7B+X0axxfAftfE3EOTgig42/IW+ATorWo5z/T0RKYomdGY+ih0utXOKJM7EpT/3ffZGQbjn5ZMAS43SmSVndraG5L4toDhxKDWA3BkkS0M=
